{
    "dag":{
        "schedule_interval": "@once",
        "py_file": "gs://${ddos_bucket}/dag_pipeline_util.py"
    },
    "beam_options": {
        "op_kwargs": {
            "BQ_PROJECT": "${project_id}",
            "BQ_DS": "batching_${random_suffix}",
            "GCS_BUCKET":  "${ddos_bucket}",
            "GCS_OBJECT_PATH": "data",
            "SOURCE_DATASET": "ddos",
            "TARGET_TABLE": "ddos",
            "SCHEMA": "field0:INTEGER,FlowID:STRING,SrcIP:STRING,SrcPort:INTEGER,DstIP:STRING,DstPort:INTEGER,Protocol:INTEGER,Timestamp:TIMESTAMP,FlowDuration:INTEGER,TotFwdPkts:INTEGER,TotBwdPkts:INTEGER,TotLenFwdPkts:FLOAT,TotLenBwdPkts:FLOAT,FwdPktLenMax:FLOAT,FwdPktLenMin:FLOAT,FwdPktLenMean:FLOAT,FwdPktLenStd:FLOAT,BwdPktLenMax:FLOAT,BwdPktLenMin:FLOAT,BwdPktLenMean:FLOAT,BwdPktLenStd:FLOAT,FlowBytss:FLOAT,FlowPktss:FLOAT,FlowIATMean:FLOAT,FlowIATStd:FLOAT,FlowIATMax:FLOAT,FlowIATMin:FLOAT,FwdIATTot:FLOAT,FwdIATMean:FLOAT,FwdIATStd:FLOAT,FwdIATMax:FLOAT,FwdIATMin:FLOAT,BwdIATTot:FLOAT,BwdIATMean:FLOAT,BwdIATStd:FLOAT,BwdIATMax:FLOAT,BwdIATMin:FLOAT,FwdPSHFlags:INTEGER,BwdPSHFlags:INTEGER,FwdURGFlags:INTEGER,BwdURGFlags:INTEGER,FwdHeaderLen:INTEGER,BwdHeaderLen:INTEGER,FwdPktss:FLOAT,BwdPktss:FLOAT,PktLenMin:FLOAT,PktLenMax:FLOAT,PktLenMean:FLOAT,PktLenStd:FLOAT,PktLenVar:FLOAT,FINFlagCnt:INTEGER,SYNFlagCnt:INTEGER,RSTFlagCnt:INTEGER,PSHFlagCnt:INTEGER,ACKFlagCnt:INTEGER,URGFlagCnt:INTEGER,CWEFlagCount:INTEGER,ECEFlagCnt:INTEGER,DownUpRatio:FLOAT,PktSizeAvg:FLOAT,FwdSegSizeAvg:FLOAT,BwdSegSizeAvg:FLOAT,FwdBytsbAvg:INTEGER,FwdPktsbAvg:INTEGER,FwdBlkRateAvg:INTEGER,BwdBytsbAvg:INTEGER,BwdPktsbAvg:INTEGER,BwdBlkRateAvg:INTEGER,SubflowFwdPkts:INTEGER,SubflowFwdByts:INTEGER,SubflowBwdPkts:INTEGER,SubflowBwdByts:INTEGER,InitFwdWinByts:INTEGER,InitBwdWinByts:INTEGER,FwdActDataPkts:INTEGER,FwdSegSizeMin:INTEGER,ActiveMean:FLOAT,ActiveStd:FLOAT,ActiveMax:FLOAT,ActiveMin:FLOAT,IdleMean:FLOAT,IdleStd:FLOAT,IdleMax:FLOAT,IdleMin:FLOAT,Label:STRING"
        },
        "runner":"DataflowRunner",
        "project":"${project_id}",
        "job_name":"ddos-etl-fea-eng-${random_suffix}",
        "donot_pickle": true,
        "no_use_public_ips": true,
        "network": "${network_id}", 
        "subnetwork": "${subnetwork_id_without_project}",
        "service_account_email": "${service_account_email}",
        "temp_location": "gs://${ddos_bucket}/temp/py_temp",
        "worker_machine_type": "e2-standard-4",
        "staging_location": "gs://${ddos_bucket}/temp/py_stage",
        "region":"${region}",
        "random_suffix":"${random_suffix}"
    },
    "vertexai_options": {
        "PROJECT_ID": "${project_id}",
        "REGION": "${region}",
        "BUCKET_NAME": "${ddos_bucket}",
        "SERVICE_ACCOUNT": "${service_account_email}",
        "RUN_FEATURE_STORE_TASK_PARAMS": {
            "RANDOM_SUFFIX": "${random_suffix}",
            "PROJECT_ID": "${project_id}",
            "REGION": "${region}",
            "SOURCE_TABLE": "ddos",
            "ONLINE_STORE_FIXED_NODE_COUNT": 1,
            "DESTINATION_DATA_SET": "stg_modeling_${random_suffix}",
            "DESTINATION_TABLE_NAME": "ddos_served_fs",
            "SOURCE_DATASET": "batching_${random_suffix}",
            "TEMP_FILE_BUCKET": "${ddos_bucket}",
            "TEMP_FILE_PATH": "temp/feature_store_output_ddos.csv",
            "OLD_FEATURE_STORE": "",
            "NEW_FEATURE_STORE": "ddos_fs_${random_suffix}",
            "FEATURE_STORE_FEATURE_NAMES": { "c0": { "value_type": "INT64" }, 
                                             "flow_id": { "value_type": "STRING" }, 
                                             "src_ip": { "value_type": "STRING" }, 
                                             "src_port": { "value_type": "INT64" }, 
                                             "dst_ip": { "value_type": "STRING" }, 
                                             "dst_port": { "value_type": "INT64" }, 
                                             "protocol": { "value_type": "INT64" }, 
                                             "timestamp": { "value_type": "STRING" }, 
                                             "flow_duration": { "value_type": "INT64" }, 
                                             "tot_fwd_pkts": { "value_type": "INT64" }, 
                                             "tot_bwd_pkts": { "value_type": "INT64" }, 
                                             "totlen_fwd_pkts": { "value_type": "DOUBLE" }, 
                                             "totlen_bwd_pkts": { "value_type": "DOUBLE" }, 
                                             "fwd_pkt_len_max": { "value_type": "DOUBLE" }, 
                                             "fwd_pkt_len_min": { "value_type": "DOUBLE" }, 
                                             "fwd_pkt_len_mean": { "value_type": "DOUBLE" }, 
                                             "fwd_pkt_len_std": { "value_type": "DOUBLE" }, 
                                             "bwd_pkt_len_max": { "value_type": "DOUBLE" }, 
                                             "bwd_pkt_len_min": { "value_type": "DOUBLE" }, 
                                             "bwd_pkt_len_mean": { "value_type": "DOUBLE" }, 
                                             "bwd_pkt_len_std": { "value_type": "DOUBLE" }, 
                                             "flow_byts_s": { "value_type": "DOUBLE" }, 
                                             "flow_pkts_s": { "value_type": "DOUBLE" }, 
                                             "flow_iat_mean": { "value_type": "DOUBLE" }, 
                                             "flow_iat_std": { "value_type": "DOUBLE" }, 
                                             "flow_iat_max": { "value_type": "DOUBLE" }, 
                                             "flow_iat_min": { "value_type": "DOUBLE" }, 
                                             "fwd_iat_tot": { "value_type": "DOUBLE" }, 
                                             "fwd_iat_mean": { "value_type": "DOUBLE" }, 
                                             "fwd_iat_std": { "value_type": "DOUBLE" }, 
                                             "fwd_iat_max": { "value_type": "DOUBLE" }, 
                                             "fwd_iat_min": { "value_type": "DOUBLE" }, 
                                             "bwd_iat_tot": { "value_type": "DOUBLE" }, 
                                             "bwd_iat_mean": { "value_type": "DOUBLE" }, 
                                             "bwd_iat_std": { "value_type": "DOUBLE" }, 
                                             "bwd_iat_max": { "value_type": "DOUBLE" }, 
                                             "bwd_iat_min": { "value_type": "DOUBLE" }, 
                                             "fwd_psh_flags": { "value_type": "INT64" }, 
                                             "bwd_psh_flags": { "value_type": "INT64" }, 
                                             "fwd_urg_flags": { "value_type": "INT64" }, 
                                             "bwd_urg_flags": { "value_type": "INT64" }, 
                                             "fwd_header_len": { "value_type": "INT64" }, 
                                             "bwd_header_len": { "value_type": "INT64" }, 
                                             "fwd_pkts_s": { "value_type": "DOUBLE" }, 
                                             "bwd_pkts_s": { "value_type": "DOUBLE" }, 
                                             "pkt_len_min": { "value_type": "DOUBLE" }, 
                                             "pkt_len_max": { "value_type": "DOUBLE" }, 
                                             "pkt_len_mean": { "value_type": "DOUBLE" }, 
                                             "pkt_len_std": { "value_type": "DOUBLE" }, 
                                             "pkt_len_var": { "value_type": "DOUBLE" }, 
                                             "fin_flag_cnt": { "value_type": "INT64" }, 
                                             "syn_flag_cnt": { "value_type": "INT64" }, 
                                             "rst_flag_cnt": { "value_type": "INT64" }, 
                                             "psh_flag_cnt": { "value_type": "INT64" }, 
                                             "ack_flag_cnt": { "value_type": "INT64" }, 
                                             "urg_flag_cnt": { "value_type": "INT64" }, 
                                             "cwe_flag_cnt": { "value_type": "INT64" }, 
                                             "ece_flag_cnt": { "value_type": "INT64" }, 
                                             "down_up_ratio": { "value_type": "DOUBLE" }, 
                                             "pkt_size_avg": { "value_type": "DOUBLE" }, 
                                             "fwd_seg_size_avg": { "value_type": "DOUBLE" }, 
                                             "bwd_seg_size_avg": { "value_type": "DOUBLE" }, 
                                             "fwd_byts_b_avg": { "value_type": "INT64" }, 
                                             "fwd_pkts_b_avg": { "value_type": "INT64" }, 
                                             "fwd_blk_rate_avg": { "value_type": "INT64" }, 
                                             "bwd_byts_b_avg": { "value_type": "INT64" }, 
                                             "bwd_pkts_b_avg": { "value_type": "INT64" }, 
                                             "bwd_blk_rate_avg": { "value_type": "INT64" }, 
                                             "subflow_fwd_pkts": { "value_type": "INT64" }, 
                                             "subflow_fwd_byts": { "value_type": "INT64" }, 
                                             "subflow_bwd_pkts": { "value_type": "INT64" }, 
                                             "subflow_bwd_byts": { "value_type": "INT64" }, 
                                             "init_fwd_win_byts": { "value_type": "INT64" }, 
                                             "init_bwd_win_byts": { "value_type": "INT64" }, 
                                             "fwd_act_data_pkts": { "value_type": "INT64" }, 
                                             "fwd_seg_size_min": { "value_type": "INT64" }, 
                                             "active_mean": { "value_type": "DOUBLE" }, 
                                             "active_std": { "value_type": "DOUBLE" }, 
                                             "active_max": { "value_type": "DOUBLE" }, 
                                             "active_min": { "value_type": "DOUBLE" }, 
                                             "idle_mean": { "value_type": "DOUBLE" }, 
                                             "idle_std": { "value_type": "DOUBLE" }, 
                                             "idle_max": { "value_type": "DOUBLE" }, 
                                             "idle_min": { "value_type": "DOUBLE" }, 
                                             "label": { "value_type": "STRING" } }
      }
    }
}
