{
    "MODEL_NAME": "${model_name}",
    "UPLOADED_NAME": "${model_name}-uploaded",
    "TRAINED_MODEL_NAME": "${model_name}-trained",
    "ENDPOINT_NAME" : "${endpoint_name}",
    "ENDPOINT_ID": "${endpoint_id}",
    "ENDPOINT_ARTIFACT_URI": "https://${region}-aiplatform.googleapis.com/v1/${endpoint_id}",
    "AI_API_ENDPOINT": "${region}-aiplatform.googleapis.com",
    "PROJECT_ID": "${project_id}",
    "REGION": "${region}",
    "BUCKET_URI": "gs://${ddos_bucket}",
    "BUCKET_NAME": "${ddos_bucket}",
    "PIPELINE_ROOT": "gs://${ddos_bucket}/pipeline_root/ddos_dataset",
    "SERVICE_ACCOUNT": "${service_account_email}",
    "SUBNETWORK": "${subnetwork_id}",
    "SUBNETWORK_SELF_LINK": "${subnetwork_self_link}",
    "RUN_FEATURE_STORE_TASK_PARAMS": {
        "PROJECT_ID": "${project_id}",
        "REGION": "${region}",
        "SOURCE_DATASET": "batching_${random_suffix}",
        "SOURCE_TABLE": "ddos",
        "SOURCE_TABLE_URI": "bq://${project_id}.batching_${random_suffix}.ddos",
        "ONLINE_STORE_FIXED_NODE_COUNT": 1,
        "DESTINATION_DATA_SET": "stg_modeling_${random_suffix}",
        "DESTINATION_TABLE_NAME": "ddos_served_fs",
        "DESTINATION_TABLE_URI": "bq://${project_id}.stg_modeling_${random_suffix}.ddos_served_fs",
        "TEMP_FILE_BUCKET": "${ddos_bucket}",
        "TEMP_FILE_PATH": "temp/feature_store_output_ddos.csv",
        "OLD_FEATURE_STORE": "",
        "NEW_FEATURE_STORE": "ddos_fs_${random_suffix}"
    },
    "RUN_AUTOML_TRAINING_TASK_PARAMS": {
        "BUCKET_URI": "gs://${ddos_bucket}",
        "BUCKET_NAME": "${ddos_bucket}",
        "TRAINED_MODEL_NAME": "${model_name}-trained",
        "ENDPOINT_NAME" : "${endpoint_name}",
        "ENDPOINT_ID": "${endpoint_id}",
        "PROJECT_ID": "${project_id}",
        "REGION": "${region}",
        "ROOT_DIR_BUCKET_NAME": "${ddos_bucket}",
        "OUTPUT_PREDICTION_DATASET": "inferenced_${random_suffix}",
        "OUTPUT_PREDICTION_TABLE": "ddos_automl_batch_predictions",
        "OUTPUT_PREDICTION_TABLE_URI": "bq://${project_id}.inferenced_${random_suffix}.ddos_automl_batch_predictions",
        "DATA_SOURCE_DATASET": "stg_modeling_${random_suffix}",
        "DATA_SOURCE_TABLE": "ddos_served_fs",
        "DATA_SOURCE_TABLE_URI": "bq://${project_id}.stg_modeling_${random_suffix}.ddos_served_fs",
        "SERVICE_ACCOUNT": "${service_account_email}",
        "CLASSIFICATION_RESULT_FEATURE": "label",
        "SUBNETWORK": "${subnetwork_id}",
        "SUBNETWORK_SELF_LINK": "${subnetwork_self_link}"
    },
    "DO_ONLINE_PREDICTION_PARAMS": {
        "PROJECT_NAME": "${project_id}",
        "PREDICTION_TABLE": "ddos_automl_online_predictions",
        "SOURCE_TABLE": "ddos_streaming",
        "SOURCE_DATASET": "streaming_${random_suffix}",
        "PREDICTION_DATASET": "inferenced_${random_suffix}",
        "REGION": "${region}",
        "INCIDENT_TOPIC_NAME": "${ddos_incidents_topic}"  
    },
    "EVALUATE_SETTINGS": {
        "model_name": "${model_name}",
        "endpoint_name": "${endpoint_name}",
        "endpoint_id": "${endpoint_id}"
    }
}
